# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/XuBookstoreOrder/api/categories
Accept: application/json

###
# curl 'http://localhost:8080/XuBookstoreOrder/api/orders' -H 'User-Agent:
POST http://localhost:8080/XuBookstoreOrder/api/orders
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Referer: http://localhost:8081/XuBookstoreOrder/checkout
Origin: http://localhost:8081
Connection: keep-alive
Content-Type: application/json

{
  "cart": {
    "items": [
      {
        "book": {
          "bookId": 1016,
          "title": "The Giver of Stars",
          "author": "Jojo Moyes",
          "price": 1402,
          "isPublic": false,
          "categoryId": 1006
        },
        "quantity": 1
      }
    ]
  },
  "customerForm": {
    "name": "toms rogers",
    "address": "123 main st",
    "phone": "4176584250",
    "email": "toms@toms.edu",
    "ccNumber": "4444333322221111",
    "ccExpiryMonth": 11,
    "ccExpiryYear": 2020
  }
}

###

